### ISSUE TITLE
Update UIWebViews to WKWebViews

### ISSUE THREAD

**Issue by chotaling1** [bluesnap/bluesnap-ios-int#13]
Apple has announced that they have deprecated the UIWebView control and will soon stop accepting app submissions that use these controls. The SDK makes use of a UIWebView in one of its ViewControllers

**Comment by chotaling1** [comment]
It looks like this issue has been implemented in the "FE-13" branch. Is there an ETA for when that branch will be rolled into a release?

**Comment by snpori** [comment]
shipped in 1.3.1
