### ISSUE TITLE
AppStore Rejection 

### ISSUE THREAD

**Issue by hardikdevios** [bluesnap/bluesnap-ios-int#16]
Hello 
You have added the New SDK `Credentialmobile` in latest `pod spec`,
But it's failing the Apple Validation because it's not properly thinned please check the Log.

![Screen Shot 2019-12-03 at 2 15 30 PM](https://user-images.githubusercontent.com/6657591/70035408-c9253700-15d8-11ea-8726-98bd5c6772e8.png)

**Comment by mp3il** [comment]
Hi,
I'm having the same issue:
```
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
```

Looking for which library:
```
 grep -r "UIWebView" .
Binary file ./Pods/BluesnapSDK/BluesnapSDK/CardinalMobile.framework/CardinalMobile matches
```

**Comment by mp3il** [comment]
@snpori Any news about that?

**Comment by snpori** [comment]
Thanks for reaching out and spotting this. we also got this feedback from others.
Currently, there are two options 
-  disable crardinal SDK, we've backed a version without 3DS and cardinal you can check out this tag: 1.3.4-nc
-  checkout branch  FE-226 which includes an updated cardinal SDK.

We will keep updating.
Thanks.

**Comment by mp3il** [comment]
Thank you!

**Comment by snpori** [comment]
This is solved with the new cardinal SDK version.
