### ISSUE TITLE
First transaction was success and rest of the transactions are showing as fraud   

### ISSUE THREAD

**Issue by tanalavijay** [bluesnap/bluesnap-ios-int#19]
Hi team,
I'am using my credit card every time the first transaction was success then next rest of the transactions are showing as fraud :-
 { StatusCodeError: 400 - {"message":[{"errorName":"FRAUD_DETECTED","code":"15011","description":"The request cannot be fulfilled for the current shopper. Please contact BlueSnap support for further details.","fraudEvents":{"fraudReferenceId":"72326937"}}]}

**Comment by snpori** [comment]
Hi.
I'm closing this issue since it's not ios-sdk specific.
As the message says, this should be resolved using Bluesnap Support.
Thanks.
