### ISSUE TITLE
Apple Pay App Rejection

### ISSUE THREAD

**Issue by kevinskrei** [bluesnap/bluesnap-ios-int#22]
Our app was just rejected for not showing the payee name in the Apple Pay Sheet. Here is the rejection:

**Guideline 3.1.6 - Business - Payments - Apple Pay**
Your app uses Apple Pay as a purchasing mechanism but does not use Apple Pay branding and user interface elements appropriately as described in the Apple Pay Human Interface Guidelines.

- Specifically, your Apple Pay sheet did not include a payee name.

It looks like in `BSApplePayViewController` that Bluesnap hard codes "Payment" in the screen so it shows up as "Pay Payment" on the sheet. **This value needs to be configurable to allow the client to set the company name** as "Pay [Company Name]" according to this: https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/checkout-and-payment/#customize-the-payment-sheet

Specifically: 
**Provide a business name after the word PAY on the same line as the total.** 
Use the same business name people will see when they look for the charge on their bank or credit card statement. This provides reassurance that payment is going to the right place. For example: PAY [COMPANY_NAME].

See hardcoded value:
https://github.com/bluesnap/bluesnap-ios-int/blob/develop/BluesnapSDK/BSApplepayViewController.swift#L23

**Comment by snpori** [comment]
Hi @kevinskrei 
Thanks for noticing this change. it seems like adding a variable to the view controller is the right approach.
I believe this will be fixed soon.

**Comment by snpori** [comment]
Fixed in recent release.
